FROM  ubuntu:14.04

RUN \
sudo  apt-get update && \
#  apt-get upgrade -y && \	
  apt-get install -y openjdk-7-jdk && \
  rm -rf /var/lib/apt/lists/*

#RUN ls -a /usr/lib/jvm/default-jvm/jre/lib/amd64/server/
#RUN ls -a /usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/amd64/server/
COPY run.sh /src/

COPY nginx.conf /src/
COPY nginx-clojure /src/nginxclojure/
COPY libjpeg62_6b1-2ubuntu1.1_amd64.deb /src/
#COPY curl_7.35.0-1ubuntu2.10_amd64.deb /src/
#COPY libs /src/libs/

#RUN ls /usr/lib/jvm/java-1.7-openjdk/
#RUN echo 'deb http://cz.archive.ubuntu.com/ubuntu trusty main' >> /etc/apt/sources.list
ENV JAVA_HOME /usr/lib/jvm/default-jvm
ENV PATH $PATH:$JAVA_HOME/bin
#RUN printenv
#RUN java -version
#RUN javac -version
#RUN apt-get install libcurl3
#RUN dpkg -i /src/curl_7.35.0-1ubuntu2.10_amd64.deb
RUN apt-get install ca-certificates  bash 
RUN dpkg -i /src/libjpeg62_6b1-2ubuntu1.1_amd64.deb
RUN apt-get install -d libjpeg62 

#RUN curl http://www.openssl.org/source/openssl-1.0.0a.tar.gz
#&& tar -xf openssl-1.0.0a.tar.gz
#&& cd openssl-1.0.0a
#&& ./config
#&& sudo make install

#RUN apk update && apk upgrade \
#&& cd /tmp \
#&& wget http://nginx.org/download/nginx-1.10.1.tar.gz  \
#&& tar xzf nginx-1.10.1.tar.gz \
#&& cd /tmp/nginx-1.10.1 \
#&& ./configure \
#   --prefix=/etc/nginx \
#    --sbin-path=/usr/sbin/nginx \
#    --conf-path=/etc/nginx/nginx.conf \
#    --error-log-path=/var/log/nginx/error.log \
#    --http-log-path=/var/log/nginx/access.log \
#    --pid-path=/var/run/nginx.pid \
#    --lock-path=/var/run/nginx.lock \
#    --with-pcre-jit \
#    --with-http_ssl_module \
#    --add-module=/src/nginxclojure/src/c \
#&&     make \
#&& make install \
#&& sed -i -e 's/#access_log  logs\/access.log  main;/access_log \/dev\/stdout;/' -e 's/#error_log  logs\/error.log  notice;/error_log stderr notice;/' /etc/nginx/nginx.conf \
#&&  rm -rf /tmp/* 

#RUN nginx -v

#RUN cp /src/nginx.conf /etc/nginx/nginx.conf

RUN chmod +x /src/run.sh

#RUN apk add ca-certificates && update-ca-certificates

RUN openssl version -v


ENTRYPOINT /src/run.sh


